spring.application.name=petshop-backend
server.port=8081
# Conexão com MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/petshop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA – cria as tabelas automaticamente (depois mude para 'update' ou 'validate')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
